language: node_js
cache:
  directories:
    # https://twitter.com/maybekatz/status/905213355748720640
    - ~/.npm
node_js:
  - '8'
  - '10'

# Trigger a push build on master branch + PRs build on every branch. Avoid
# double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

stages:
  - commitlint
  - test

jobs:
  include:
    - stage: commitlint
      node_js: '8'
      script: commitlint-travis
    - stage: test
      script: npm test